import 'package:flutter/material.dart';

// --- DİL ALTYAPISI (LOCALIZATION) ---
final ValueNotifier<String> appLanguage = ValueNotifier('tr');

final Map<String, Map<String, String>> translations = {
  'tr': {
    'app_title': 'AI Auto Studio',
    'welcome_title': '3D Modelleme Ve Modifiye Dünyasına Hoş Geldin',
    'username': 'Kullanıcı Adı',
    'password': 'Şifre',
    'login': 'Giriş Yap',
    'no_account': 'Hesabın Yok Mu? ',
    'signup': 'Kayıt Ol',
    'welcome_user': 'HOŞ GELDİN,',
    'design_dream': 'Hayalindeki\nAracı Tasarla',
    'ai_step': 'AI İle 3D Modifiye Ve Görselleştirme Dünyasına Adım At.',
    'new_project': 'Yeni Proje Başlat',
    'total': 'Toplam',
    'cars_in_garage': 'Araç Garajda',
    'created': 'Oluşturuldu',
    'credit': 'Kredi',
    'available': 'Kullanılabilir',
    'my_garage': 'Garajım',
    'see_all': 'Tümünü Gör',
    'completed': 'Tamamlandı',
    'edit': 'Düzenle',
    'drafts': 'Taslaklar',
    'unfinished_wheel': 'Jant Seçimi Yarım Kaldı',
    'continue_btn': 'Devam Et',
    'delete_draft': 'Sil',
    'draft_deleted': 'Taslak başarıyla silindi!',
    'home_tab': 'Ana Sayfa',
    'discover_tab': 'Keşfet',
    'store_tab': 'Mağaza',
    'profile_tab': 'Profil',
    'exit_app': 'Uygulamadan Çık',
    'exit_sure': 'Çıkmak İstediğinize Emin Misiniz?',
    'no': 'Hayır',
    'yes': 'Evet',
    'discover_title': 'Keşfet 🌍',
    'discover_desc': 'Topluluğun En Alevli Tasarımlarına Göz At.',
    'by': 'Yapan: ',
    'share_your_legend': 'Efsaneni Toplulukla Paylaş 🚀',
    'store_title': 'Mağaza',
    'store_desc': 'Projelerini Hayata Geçirmek İçin Kredi Satın Al.',
    'faq': 'Yardım Ve Destek (SSS)',
    'invite_friend': 'Arkadaşını Davet Et 🤝\n(+50 Kredi)',
    'packages': 'Paketler',
    'ideal_single': 'Tekli Projeler İçin İdeal',
    'bonus_50': '+50 Bonus',
    'design_enthusiasts': 'Tasarım Tutkunlarına',
    'best_deal': '🔥 En İyi Fırsat',
    'most_preferred': '👑 EN ÇOK TERCİH EDİLEN',
    'weekly_unlimited': 'Haftalık Sınırsız',
    'fast_render': '⚡ Sıra Beklemeden Hızlı Render',
    'premium_wheels': '🛞 Premium Jantlar',
    'unlimited_colors': '🎨 Sınırsız Renk Paleti',
    'total_renders': 'Toplam Render: ',
    'active_balance': 'Aktif Bakiye',
    'top_up': 'Yükle',
    'settings': 'Ayarlar',
    'lang_select': '🌐 Dil Seçimi (Language)',
    'theme_color': '🎨 Tema Ve Arka Plan Rengi',
    'edit_user': '👤 Kullanıcı Bilgilerini Düzenle',
    'history': '📜 Geçmiş İşlemler',
    'logout': '🚪 Çıkış Yap',
    'upload_photo': 'Fotoğraf Yükleme',
    'turn_3d': 'Aracını 3 Boyutlu\nHale Getirelim',
    'upload_desc': 'AI Modelleme İçin Aracınızın 4 Farklı\nAçıdan Çekilmiş Net Fotoğraflarını\nYükleyin.',
    'turn_2d': 'Aracını 2 Boyutlu\nModifiye Edelim',
    'upload_desc_2d': 'AI Modifiye İçin Aracınızın Net Bir\nFotoğrafını Yükleyin.',
    'front': 'Ön',
    'right_side': 'Sağ Yan',
    'left_side': 'Sol Yan',
    'rear': 'Arka',
    'single_photo': 'Fotoğraf',
    'mod_selection': 'Modifikasyon Seçimi',
    'preview_area': 'Önizleme Alanı',
    'color_palette': 'Renk Paleti',
    'wheel_options': 'Jant Seçenekleri',
    'start_prod': 'Üretimi Başlat',
    'not_enough_credit': 'Kredin Yetersiz Mi? Kredi Satın Al',
    'completed_up': 'TAMAMLANDI',
    'ai_processing': 'AI İŞLİYOR...',
    'ready': 'Hazır!',
    'remaining': 'Kalan: ',
    'min': 'Dk',
    'sec': 'Sn',
    'score': 'Skor: ',
    'best': 'En İyi: ',
    'close_call': 'KIL PAYI!\n+50',
    'render_finished': 'RENDER BİTTİ!',
    'crashed': '💥 KAZA YAPTIN!',
    'play_again': 'Tekrar Oyna',
    'top_of_week': 'Haftanın En İyileri',
    'coming_soon': '... (Çok Yakında)',
    'community_legends': 'Topluluğun Efsaneleri (Haftanın En İyileri)',
    'return_garage': 'Garaja Dön',
    'all_my_cars': 'Tüm Araçlarım',
    'select_lang_title': 'Dil Seçin / Select Language',
    'hours_ago': '2 Saat Önce',
    'yesterday': 'Dün',
    'days_ago': '3 Gün Önce',
    'standard': 'Standart',
    'wheel_name': 'Jant',
    'edit_profile_photo': 'Profil Fotoğrafını Düzenle',
    'take_photo': 'Kameradan Çek 📸',
    'choose_gallery': 'Galeriden Seç 🖼️',
    'coming_soon_toast': 'Bu Özellik Çok Yakında Aktif Olacak! 🚀',
    'select_avatar': 'Hazır Avatarlar',
    'select_project_type': 'Proje Tipini Seç',
    '2d_mod': '2D Fotoğraf Modifiyesi',
    '2d_desc': 'Tek bir fotoğraf üzerinden anında modifiye yap.',
    '3d_mod': '3D Model Çıkarma',
    '3d_desc': '4 farklı açıdan aracını 3 boyutlu modele çevir.',
    'photo_source': 'Fotoğraf Kaynağı',
    'level': 'Seviye',
    'apprentice': 'Çırak',
    'journeyman': 'Kalfa',
    'master': 'Usta',
    'senior': 'Kıdemli',
    'grandmaster': 'Baş Usta',
    'all_ranks': 'Tüm Rütbeler Ve Seviyeler',
    'target': 'Hedef',
    'max_level': 'Maksimum Seviye',
    'renders_needed': 'Render',
    'current_rank': 'Şu Anki Rütben',
  },
  'en': {
    'app_title': 'AI Auto Studio',
    'welcome_title': 'Welcome To The World Of 3D Modeling And Tuning',
    'username': 'Username',
    'password': 'Password',
    'login': 'Log In',
    'no_account': 'Don\'t Have An Account? ',
    'signup': 'Sign Up',
    'welcome_user': 'WELCOME,',
    'design_dream': 'Design Your\nDream Car',
    'ai_step': 'Step Into The World Of 3D Tuning And Visualization With AI.',
    'new_project': 'Start New Project',
    'total': 'Total',
    'cars_in_garage': 'Cars In Garage',
    'created': 'Created',
    'credit': 'Credits',
    'available': 'Available',
    'my_garage': 'My Garage',
    'see_all': 'See All',
    'completed': 'Completed',
    'edit': 'Edit',
    'drafts': 'Drafts',
    'unfinished_wheel': 'Wheel Selection Unfinished',
    'continue_btn': 'Continue',
    'delete_draft': 'Delete',
    'draft_deleted': 'Draft successfully deleted!',
    'home_tab': 'Home',
    'discover_tab': 'Discover',
    'store_tab': 'Store',
    'profile_tab': 'Profile',
    'exit_app': 'Exit App',
    'exit_sure': 'Are You Sure You Want To Exit?',
    'no': 'No',
    'yes': 'Yes',
    'discover_title': 'Discover 🌍',
    'discover_desc': 'Check Out The Hottest Designs From The Community.',
    'by': 'By: ',
    'share_your_legend': 'Share Your Legend 🚀',
    'store_title': 'Store',
    'store_desc': 'Buy Credits To Bring Your Projects To Life.',
    'faq': 'Help & Support (FAQ)',
    'invite_friend': 'Invite a Friend 🤝\n(+50 Credits)',
    'packages': 'Packages',
    'ideal_single': 'Ideal For Single Projects',
    'bonus_50': '+50 Bonus',
    'design_enthusiasts': 'For Design Enthusiasts',
    'best_deal': '🔥 Best Deal',
    'most_preferred': '👑 MOST PREFERRED',
    'weekly_unlimited': 'Weekly Unlimited',
    'fast_render': '⚡ Fast Render Without Queue',
    'premium_wheels': '🛞 Premium Wheels',
    'unlimited_colors': '🎨 Unlimited Color Palette',
    'total_renders': 'Total Renders: ',
    'active_balance': 'Active Balance',
    'top_up': 'Top Up',
    'settings': 'Settings',
    'lang_select': '🌐 Language Selection',
    'theme_color': '🎨 Theme And Background Color',
    'edit_user': '👤 Edit User Information',
    'history': '📜 Transaction History',
    'logout': '🚪 Log Out',
    'upload_photo': 'Upload Photo',
    'turn_3d': 'Let\'s Turn Your Car\nInto 3D',
    'upload_desc': 'Upload Clear Photos Of Your Car From 4 Different Angles For AI Modeling.',
    'turn_2d': 'Let\'s Modify Your\n2D Photo',
    'upload_desc_2d': 'Upload A Clear Photo Of Your Car For AI Modification.',
    'front': 'Front',
    'right_side': 'Right Side',
    'left_side': 'Left Side',
    'rear': 'Rear',
    'single_photo': 'Photo',
    'mod_selection': 'Modification Selection',
    'preview_area': 'Preview Area',
    'color_palette': 'Color Palette',
    'wheel_options': 'Wheel Options',
    'start_prod': 'Start Production',
    'not_enough_credit': 'Not Enough Credits? Buy Credits',
    'completed_up': 'COMPLETED',
    'ai_processing': 'AI PROCESSING...',
    'ready': 'Ready!',
    'remaining': 'Remaining: ',
    'min': 'Min',
    'sec': 'Sec',
    'score': 'Score: ',
    'best': 'Best: ',
    'close_call': 'CLOSE CALL!\n+50',
    'render_finished': 'RENDER FINISHED!',
    'crashed': '💥 YOU CRASHED!',
    'play_again': 'Play Again',
    'top_of_week': 'Top Of The Week',
    'coming_soon': '... (Coming Soon)',
    'community_legends': 'Community Legends (Top Of The Week)',
    'return_garage': 'Return To Garage',
    'all_my_cars': 'All My Cars',
    'select_lang_title': 'Select Language / Dil Seçin',
    'hours_ago': '2 Hours Ago',
    'yesterday': 'Yesterday',
    'days_ago': '3 Days Ago',
    'standard': 'Standard',
    'wheel_name': 'Wheel',
    'edit_profile_photo': 'Edit Profile Photo',
    'take_photo': 'Take Photo 📸',
    'choose_gallery': 'Choose From Gallery 🖼️',
    'coming_soon_toast': 'This Feature Will Be Available Very Soon! 🚀',
    'select_avatar': 'Ready Avatars',
    'select_project_type': 'Select Project Type',
    '2d_mod': '2D Photo Modification',
    '2d_desc': 'Instantly modify a single photo.',
    '3d_mod': '3D Model Generation',
    '3d_desc': 'Turn your car into a 3D model from 4 angles.',
    'photo_source': 'Photo Source',
    'level': 'Level',
    'apprentice': 'Apprentice',
    'journeyman': 'Journeyman',
    'master': 'Master',
    'senior': 'Senior',
    'grandmaster': 'Grandmaster',
    'all_ranks': 'All Ranks And Levels',
    'target': 'Target',
    'max_level': 'Max Level',
    'renders_needed': 'Renders',
    'current_rank': 'Current Rank',
  }
};

String t(String key) {
  return translations[appLanguage.value]?[key] ?? key;
}

// PREMIUM SKOR VE SAYI FONT STİLİ
final TextStyle premiumNumberStyle = const TextStyle(
  fontWeight: FontWeight.bold,
  fontFamily: 'Roboto',
  letterSpacing: 1.1,
);